### ISSUE TITLE
Wifi Rev2 Errors when downloading

### ISSUE THREAD

**Issue by TimEllis2019** [arduino/nina-fw#21] opened 2019-04-28 02:08 UTC
I just tried to load some code to my Wifi Rev2 and got the following error.

```
/home/builder/opt/arduino-builder/arduino-builder -compile -core-api-version 10611 -hardware /home/builder/opt/arduino-builder/hardware -hardware /home/builder/.arduino15/packages -tools /home/builder/opt/arduino-builder/tools -tools /home/builder/.arduino15/packages -built-in-libraries /home/builder/opt/libraries/latest -logger humantags -fqbn arduino:megaavr:uno2018:mode=on -build-cache /tmp -build-path /tmp/706489884/build -verbose -prefs runtime.tools.CMSIS.path=/home/builder/.arduino15/packages/arduino/tools/CMSIS/4.5.0 -prefs runtime.tools.bossac.path=/home/builder/.arduino15/packages/arduino/tools/bossac/1.7.0 -prefs runtime.tools.flashpack.path=/home/builder/.arduino15/packages/Intel/tools/flashpack/2.0.0 -prefs runtime.tools.openocd.path=/home/builder/.arduino15/packages/arduino/tools/openocd/0.10.0-arduino7 -prefs runtime.tools.core2-32-poky-linux.path=/home/builder/.arduino15/packages/Intel/tools/core2-32-poky-linux/1.6.2+1.0 -prefs runtime.tools.linuxuploader.path=/home/builder/.arduino15/packages/arduino/tools/linuxuploader/1.5.1 -prefs runtime.tools.CMSIS-Atmel.path=/home/builder/.arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0 -prefs runtime.tools.x86-linux-gcc.path=/home/builder/.arduino15/packages/arduino/tools/x86-linux-gcc/7.2.0 -prefs runtime.tools.arm-linux-gcc.path=/home/builder/.arduino15/packages/arduino/tools/arm-linux-gcc/4.9.3 -prefs runtime.tools.arm-none-eabi-gcc.path=/home/builder/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4 -prefs runtime.tools.dfu-util.path=/home/builder/.arduino15/packages/arduino/tools/dfu-util/0.9.0-arduino1 -prefs runtime.tools.arduinoOTA.path=/home/builder/.arduino15/packages/arduino/tools/arduinoOTA/1.2.1 -prefs runtime.tools.sketchUploader.path=/home/builder/.arduino15/packages/Intel/tools/sketchUploader/1.6.2+1.0 -prefs runtime.tools.nrf5x-cl-tools.path=/home/builder/.arduino15/packages/arduino/tools/nrf5x-cl-tools/9.3.1 -prefs runtime.tools.i586-poky-linux-uclibc.path=/home/builder/.arduino15/packages/Intel/tools/i586-poky-linux-uclibc/1.6.2+1.0 -prefs runtime.tools.arc-elf32.path=/home/builder/.arduino15/packages/Intel/tools/arc-elf32/1.6.9+1.0.1 -prefs runtime.tools.arduino101load.path=/home/builder/.arduino15/packages/Intel/tools/arduino101load/2.0.1 -prefs runtime.tools.avr-gcc.path=/home/builder/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2 -prefs runtime.tools.avrdude.path=/home/builder/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino14 -libraries /tmp/706489884/custom -libraries /tmp/706489884/pinned /tmp/706489884/Temp_controller

Using board 'uno2018' from platform in folder: /home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25

Using core 'arduino' from platform in folder: /home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25

Detecting libraries used...

/home/builder/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega4809 -DF_CPU=16000000L -DARDUINO=10611 -DARDUINO_AVR_UNO_WIFI_REV2 -DARDUINO_ARCH_MEGAAVR -DUNO_WIFI_REV2_328MODE -I/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/cores/arduino/api/deprecated -I/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/cores/arduino -I/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/variants/uno2018 /tmp/706489884/build/sketch/Temp_controller.ino.cpp -o /dev/null

Generating function prototypes...

/home/builder/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega4809 -DF_CPU=16000000L -DARDUINO=10611 -DARDUINO_AVR_UNO_WIFI_REV2 -DARDUINO_ARCH_MEGAAVR -DUNO_WIFI_REV2_328MODE -I/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/cores/arduino/api/deprecated -I/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/cores/arduino -I/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/variants/uno2018 /tmp/706489884/build/sketch/Temp_controller.ino.cpp -o /tmp/706489884/build/preproc/ctags_target_for_gcc_minus_e.cpp

/home/builder/opt/arduino-builder/tools/ctags/5.8-arduino11/ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /tmp/706489884/build/preproc/ctags_target_for_gcc_minus_e.cpp

Compiling sketch...

/home/builder/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega4809 -DF_CPU=16000000L -DARDUINO=10611 -DARDUINO_AVR_UNO_WIFI_REV2 -DARDUINO_ARCH_MEGAAVR -DUNO_WIFI_REV2_328MODE -I/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/cores/arduino/api/deprecated -I/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/cores/arduino -I/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/variants/uno2018 /tmp/706489884/build/sketch/Temp_controller.ino.cpp -o /tmp/706489884/build/sketch/Temp_controller.ino.cpp.o

Compiling libraries...

Compiling core...

/home/builder/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega4809 -DF_CPU=16000000L -DARDUINO=10611 -DARDUINO_AVR_UNO_WIFI_REV2 -DARDUINO_ARCH_MEGAAVR -DUNO_WIFI_REV2_328MODE -I/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/cores/arduino/api/deprecated -I/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/cores/arduino -I/home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/variants/uno2018 /home/builder/.arduino15/packages/arduino/hardware/megaavr/1.6.25/variants/uno2018/variant.c -o /tmp/706489884/build/core/variant.c.o

Using precompiled core: /tmp/core/core_arduino_megaavr_uno2018_mode_on_3904bbeaf935065271a887605e538632.a

Linking everything together...

/home/builder/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-gcc -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega4809 -o /tmp/706489884/build/Temp_controller.ino.elf /tmp/706489884/build/sketch/Temp_controller.ino.cpp.o /tmp/706489884/build/core/variant.c.o /tmp/706489884/build/../../core/core_arduino_megaavr_uno2018_mode_on_3904bbeaf935065271a887605e538632.a -L/tmp/706489884/build -lm

/home/builder/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-objcopy -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0 /tmp/706489884/build/Temp_controller.ino.elf /tmp/706489884/build/Temp_controller.ino.eep

/home/builder/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-objcopy -O ihex -R .eeprom /tmp/706489884/build/Temp_controller.ino.elf /tmp/706489884/build/Temp_controller.ino.hex

/home/builder/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/avr-size -A /tmp/706489884/build/Temp_controller.ino.elf

Sketch uses 8464 bytes (17%) of program storage space. Maximum is 49152 bytes.

Global variables use 304 bytes (4%) of dynamic memory, leaving 5840 bytes for local variables. Maximum is 6144 bytes.

Programming with: Serial

Flashing with command:C:/Users/telli/.arduino-create/arduino/avrdude/6.3.0-arduino14/bin/avrdude.exe -CC:/Users/telli/.arduino-create/arduino/avrdude/6.3.0-arduino14/etc/avrdude.conf -v -patmega4809 -cxplainedmini_updi -Pusb -b115200 -e -D -Uflash:w:C:/Users/telli/AppData/Local/Temp/arduino-create-agent665699992/Temp_controller.hex:i -Ufuses:w:C:/Users/telli/AppData/Local/Temp/extrafiles169525015/fuses/fuses_4809.bin:r

avrdude: Version 6.3-20171130

Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/

Copyright (c) 2007-2014 Joerg Wunsch

System wide configuration file is "C:/Users/telli/.arduino-create/arduino/avrdude/6.3.0-arduino14/etc/avrdude.conf"

Using Port : usb

Using Programmer : xplainedmini_updi

Overriding Baud Rate : 115200

avrdude: Found CMSIS-DAP compliant device, using EDBG protocol

AVR Part : ATmega4809

Chip Erase delay : 0 us

PAGEL : P00

BS2 : P00

RESET disposition : dedicated

RETRY pulse : SCK

serial program mode : yes

parallel program mode : yes

Timeout : 0

StabDelay : 0

CmdexeDelay : 0

SyncLoops : 0

ByteDelay : 0

PollIndex : 0

PollValue : 0x00

Memory Detail :

Block Poll Page Polled

Memory Type Mode Delay Size Indx Paged Size Size #Pages MinW MaxW ReadBack

----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------

signature 0 0 0 0 no 3 0 0 0 0 0x00 0x00

prodsig 0 0 0 0 no 61 61 0 0 0 0x00 0x00

fuses 0 0 0 0 no 9 0 0 0 0 0x00 0x00

fuse0 0 0 0 0 no 1 0 0 0 0 0x00 0x00

fuse1 0 0 0 0 no 1 0 0 0 0 0x00 0x00

fuse2 0 0 0 0 no 1 0 0 0 0 0x00 0x00

fuse4 0 0 0 0 no 1 0 0 0 0 0x00 0x00

fuse5 0 0 0 0 no 1 0 0 0 0 0x00 0x00

fuse6 0 0 0 0 no 1 0 0 0 0 0x00 0x00

fuse7 0 0 0 0 no 1 0 0 0 0 0x00 0x00

fuse8 0 0 0 0 no 1 0 0 0 0 0x00 0x00

lock 0 0 0 0 no 1 0 0 0 0 0x00 0x00

data 0 0 0 0 no 0 0 0 0 0 0x00 0x00

usersig 0 0 0 0 no 64 64 0 0 0 0x00 0x00

flash 0 0 0 0 no 49152 128 0 0 0 0x00 0x00

eeprom 0 0 0 0 no 256 64 0 0 0 0x00 0x00

Programmer Type : JTAGICE3_UPDI

Description : Atmel AVR XplainedMini in UPDI mode

ICE hardware version: 0

ICE firmware version: 1.19 (rel. 57)

Serial number : B8439DC837CB552DC3A7

Vtarget : 5.00 V

JTAG clock megaAVR/program: 0 kHz

JTAG clock megaAVR/debug: 0 kHz

JTAG clock Xmega: 0 kHz

PDI clock Xmega : 0 kHz

avrdude: Partial Family_ID returned: "mega"

avrdude: AVR device initialized and ready to accept instructions

Reading | avrdude: bad response to enter progmode command: 0xa0

avr_read(): error reading address 0x0000

read operation failed for memory "signature"

avrdude: error reading signature data for part "ATmega4809", rc=-67

avrdude: error reading signature data, rc=-67

avrdude done. Thank you.
```

**Comment by facchinm** [comment] 2019-04-29 08:00
Closing as duplicate of https://github.com/arduino/Arduino/issues/8816, not nina-fw related

**Closed by facchinm** 2019-04-29 08:00 UTC
